# Setup
title:        Navy Xie's Site
tagline:      Technologies sharing
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Navy Xie
  url:        http://navy-xie.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
