# Basic
title: Navy Xie's Blog
subtitle: We are all in the gutter, but some of us are looking at the stars.
welcome_message: Welcome to my blog
description: Full-stack developer, experienced on iOS development, currently researching in AI area
creator: <a href="https://www.navyxie.cn">Navy Xie</a>

url: "https://www.navyxie.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Blog

# Navigation buttons in the front page.
nav:
    # - {title: 成长, description: 成长历程, url: 'growup'}
    # - {title: 简历, description: 简历, url: 'resume'}
    # - {title: 关于, description: 关于, url: 'about'}
    # - {title: 项目, description: 项目, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    github: navy-xie
    mail: navy.xie@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
